### ISSUE TITLE
bug: 投稿できず（赤字の部分、いれているはず）

### ISSUE THREAD

**Issue by taisukef** [jigintern/2023-spring#31]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/1715217/227389945-013f61b8-f6ca-4d65-a98b-edf0a9eb4e01.png">

**Comment by FukushimaRyosuke** [comment]
コメントありがとうございます。改善させていただきました

**Comment by taisukef** [comment]
ありがとう！
